"""H617A scene catalogue — generated from Govee API for H617A."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SceneEntry:
    code: int
    param: str = ""

    @property
    def is_simple(self) -> bool:
        return not self.param


# fmt: off
_RAW: dict[str, tuple[int] | tuple[int, str]] = {
    "sunrise": (0,),
    "sunset": (1,),
    "forest": (2163, "AyYAAQAKAgH/GQG0CgoCyBQF//8AAP//////AP//lP8AFAGWAAAAACMAAg8FAgH/FAH7AAAB+goEBP8AtP8AR///4/8AAAAAAAAAABoAAAABAgH/BQHIFBQC7hQBAP8AAAAAAAAAAA=="),
    "aurora": (2164, "AiAAAAABAgH/MgEAAAAA+jIDAP8AAP//qv8AAwCAAAAAACMAAAADAgH/GQD6AAAC+gAEf/8A//8AoP//AP//FAH6AAD/AA=="),
    "lightning": (2165, "ASmBAgEBAgH/AAH/AQEC/yMG////AAAA////AAAA////AAAAFQXMEQXNAA=="),
    "starry sky": (2166, "AiAAAAACAAH/GQF4MjICyDIDAAD/AH7/AAD/AAAAAAAAACMAAg8DAAH/FAH6FBQC/TIEAAD/////AOz/AAD/AAAAAAAAAA=="),
    "spring": (2167, "AykAAgoFAgH/GQAAAAAC+jIG/zgA/38AAP8AAAAAAP//iwD/AACAAAAAACMAAh4KAAH//wAAAAAB+gAE8QAd/3UA/8AA/0sAAAD/AAH6AB0AAAABAAEyAAHIMjICyDICAP8A//8AAAAAAAAAAA=="),
    "summer": (2168, "AhoAAAABAgH//wAAAAAA/zIBM///AwCAAAAAACYAAh4KAAH//wAAAAAA+gAFAAD/AP///8AA//8AAAX/AAAAAAD/AA=="),
    "fall": (2169, "AhoAAAABAgH//wAAAAAA/zIB/zgAAwCAAAAAACkAAh4KAAH//wAAAAAA+gAG8QAd/3UA/8AA/0sA/wAAAAAAEADcAAD/AA=="),
    "winter": (2170, "AxoAAAABAgH/CgHIFAoA/TIB////AwCAAAAAACMAAh4KAAH/BQCgFBQB/QAE////t///pv//d///FAHIEQH9/yMAAh4KAAH/BQCgFBQB/QoE////t///pv//d///EQHIEgH8AA=="),
    "rainbow": (22,),
    "fire": (2171, "BR0AAAAWAAFwMgO7FBQC1RQC/1kH////AwD/EwD/ASknAAAFAgH/mQL/Xx4CAP8GAAAA/////20H/00H/w4H/wgJEgD8EACAAikhAAAGAgH/mQL/Xx4CAP8GAAAA/////20H/00H/w4H/wgJEAD+EAD9AilDAhQUAAH//wCAFBQB6hQG/xUH/wgJ/wgJ/ykH/wcTAAAAEwD8AACAAykkAAABAAH/AACAFBQB6RQG/xUH/zkH/44H/14H/wcT/w8HFwD5AAD/BA=="),
    "wave": (2172, "ASMAAAACAAH//wAAAAAC/TIEAAD/AH7/AOz/AAD/EwH8AAAAAA=="),
    "deep sea": (2173, "Ah0AAAABAAH//wAAAAAA3DICAGT/AAD/AAAAAAAAABoAAgoBAgH/KAHXAAAAADIBAP+WAAAAAAAAAA=="),
    "karst cave": (2174, "AyYAAQAKAgH/GQFkCgoCyBQFvQD//0kA/5YAnv8AFP//FgFkAAAAACkAAh4PAgH/ZAHmAAAB+hQGBP8AAP8AiwD//0v/8QAe//8AAAAAAAAAACAAAAABAAGWMgDmFBQC+hQDAMz/AG7/AAP/AAAAAAAAAA=="),
    "glacier": (2175, "BCBQAQAZAAH/AAD/MjICZAADAAD/AP//////FgD/AAAAACBVAQAZAAH/AAD/MjICZAADAAD/AP//////FAD/AAAAACkAAh4FAAH/AAL/MjIC/xQGAP//AAAA////AAAA////AP//AAAAEgD6ACYAAh4FAAH/AAL/MjIC3AIFAP//AAAA////AAAAAP//AAAAEgDrAA=="),
    "gobi desert": (2176, "AiCgAQAyAAGWlgAAAAAA3BQDljIAyDwA0jIAAAAAAAAAAB0AAgUBAAH/FAHwFFAC+kYC/38A/7QAAAAAAAAAAA=="),
    "moonlight": (2177, "AiBgAgoFAgFkZABkAAAC/RQD//8A//+g////AAAAEAXcAB2gAQAyAAFkHgAAAAAA/RQCAABQAB6gAAAAAAAAAA=="),
    "flower field": (2178, "AiygAh4ZAgH/lgDSAAAC/gAH0QBe/wMA/2wA//8A/38A/wAA9QD/AAAAEADwABqgAQAyAAEyFAAAAAAA+hQBzwBiAAAAAAAAAA=="),
    "downpour": (2179, "BCMwAgQBAAH/AAL/AgIA/2QE////AAAAAAAAAAAAAACAEQD0ACkUAgIBAAH/AAD/AQQA/yYGAAAAAAAA////AAAA////AAAAAACAEwDfAC9CAgUDAAL/AAL/AgH/AAD7KMgA/x4GAAAAAAAAAAAAAAAA////AAAAAACAAACAACAAAAAyAgIHAgGbgMgEAwOZfMAAgBQB////AACAAACAAA=="),
    "sunny": (2180, "Ax0AAAABAAHxwwB/FBQAkgICAP//AAD/AAB/AAB/AR0AAhkBAAHxwwDKFBQAfxQC////AAAAAAB/EQD8AR0AAhkBAAHxwwDKFBQAfxQC////AAAAAAB/EwD8AQ=="),
    "volcano": (2181, "BSNQAQAFAgH/CgD6AAACAAAE/wAAyAAAlgAAMgAAFgH5AAAAACNVAQAFAgH/CgD6AAACAAAE/wAAyAAAlgAAMgAAFAH6AAAAACNVAQAFAgH/CgD6AAACAAAE/wAAyAAAlgAAMgAAFAH6AAAAACNQAQAFAgH/CgD6AAACAAAE/wAAyAAAlgAAMgAAFgH5AAAAAB2gAgoFAgH/CgD/AAACAAACMgAA/wAAEADJAAAAAA=="),
    "cornfield": (2182, "Bh0wAQADAgH/AAD/FBQA5xQC/0EA/4IAEQDyAAAAAB0yAQADAgH/AAD/FBQA5hQC/0EA/2MAEQDyAAAAAB00AQADAgH/AAD/FBQA5hQC/0EA/2MAEQDyAAAAAB02AQADAgH/AAD/FBQA5xQC/0EA/5YAEQDyAAAAAB0oAQACAgH/AAD/FBQA5h4C/0EA/2MAEQDyAAAAABqgAQAyAAFkCgAAAAAA/zIBPCMAERTwAAAAAA=="),
    "meteor shower": (2183, "AiA3AQAAAgH/qwIAAAABAAADAAD/AP//////AAD6EAH1ACAwAQADAgH/qwIAAAABAAADAAD/AP//////AAD6EAH5AA=="),
    "flying": (2184, "Ax0AAgYDAgG9YgPMCgoDxhQC/44H/wYVBADQAQD5BSMAAgUCAgHbWQPMCg8DzRQE7Tj+//sHSO3+Of5dBADQAQD5BSAAAAABAAHMzAK+CgoA7kYD/26Y/1MN/9gvAACAAACAAQ=="),
    "tree shadow": (2185, "Ah0AAAABAAGnVQO+Dw+A6RQCdP5eUP4IAACAAACAACkAAgYBAAGPRgPLBQoA6RQG/+0w5/9jAAAAAAAA//8AAAAABQDjAAD7AA=="),
    "cherry blossoms": (2186, "Ah0AAAABAAFwcACAFBQA3BQC/zft/wb+AACAAACAAB0AAgUBAAE9GgCAFBQBgBQC/2r39Iv+AACAEgD1AA=="),
    "stream": (2187, "Ax2RAAACAgGdgwAAFBQAABQCW/+1VSr/FAP4AACAABoQAAABAAG1tQAAFBQA/xQBLpT/AACAAACAABqRAAACAgH/TALRFBQAABQBeP7ZBAD9AADpAA=="),
    "ripple": (2188, "BRoAAAABAAH/AACAFBQAgBQBAAD/AACAAACAABpQAAABAAH/AACAFBQAgBQBAP//FgD5AACAABpVAAABAAH/AACAFBQAgBQBAP//FAD5AACAABoyAAABAAHMzACAFBQAgBQBCP9wFgD5AACAARo1AAABAAHMzACAFBQAgBQBCP97FAD5AACAAQ=="),
    "desert b": (10005, "AyYAAAAFAgHLMwPJFBQDABQF/x4H/zcH/1oH/zcH/x4HAACAAACAABpQAwECAAH/AACAFBQAgBQB/zIHFgD5AACAABpVAwECAAH/AACAFBQAgBQB/zEHFAD5AACAAA=="),
    "sand grains": (10006, "Ah0AAwQEAAGgoAAAFBQDABQC/4Mw/4UjAACAEAH3ARoAAAABAAH/jAH5FBQDAAcB/2MaAACAAACAAA=="),
    "christmas": (2189, "AykAAgoFAgH/GQAAAAAC+jIG/zgA/38AAP8AAAAAAP///wAAFAH6AAAAACMAAg8DAAH/GQHmMjIB+jIE8QAdAP8AAP//////FgH6EgHcACAAAAABAgH/AAD+FBQA/xQD/wAAAAAAAP8AEQCAAAAAAA=="),
    "halloween": (1173, "gwb/9QAFAP///wUA/+n/BQD///8FAP/p2QUA//j/BgAE/x4A/1oA/zIA/3gA"),
    "candlelight": (9,),
    "birthday": (2190, "Ai8AAgoFAgL/GQAAAAD/GQAAAAAC+jIG/zgA/38AAP8AAAAAAP//iwD/AACAAAAAACMAAh4KAAH//wAAAAAB+gAE8QAd/3UA/8AA/0sAAAD/AAH6AA=="),
    "fireworks": (2191, "BCNQAQAZAAH/AAD/MjICZAAE/wAAAAD/AP//////FAD/AAAAACNVAQAZAAH/AAD/MjICZAAE/wAAAAD/AP//////FgD/AAAAACkAAg8FAAH/AAL/MjIC/wIG/wAAAAAA//8AAAAAAAD/AP//AAAAEgH6ACkAAg8FAAH/AAL/MjIC/wIGiwD/AAAA//8AAAAA/3L/AP//AAAAEgH6AA=="),
    "party": (2192, "AzgAAh4KAgH/GQEUAAAC/xQL/wAAAP//AAD/////AAD//wAAiwD/AAAA////AP8AiwD/AAD/AAAAACwAAh4PAgH/GQMAMjIC+gAH/wAAAP//AAD/////AAD//wAAiwD/FADIAAAAACAAAAABAAEyMgAAMjIC/woD/xP//38AAAD/EQCAAAAAAA=="),
    "dance party": (2193, "AiwAAh4PAgH/GQEUAAAC+gAH/wAAAP//AAD/////AAD//wAAiwD/AAD/AAAAACwAAh4PAgH/GQMAMjIC+gAH/wAAAP//AAD/////AAD//wAAiwD/AAAAAAAAAA=="),
    "mother's day": (2194, "AiAAAAABAAH//wEAAAAA3DID/wsA6QD/zAD/AAAAAAAAACAAAigBAgH/KAHXIBQAADID/3///z8A////AAAAAAAAAA=="),
    "father's day": (2195, "Ah0AAAABAAH//wEAAAAA3DICAAD/AP//AAAAAAAAABoAAigBAgH/KAHXIBQAADIB////AAAAAAAAAA=="),
    "white light": (10565, "ARoAAAABAAH//wAAFBQAABQB/5Y+AACAAACAAA=="),
    "sweet": (1170, "gwH/tP8yAATwAB7qACu8AP/jAP8="),
    "romantic": (7,),
    "movie": (4,),
    "siren": (2196, "Ah0AAAAKAAH//wAAAAAC/xQC/wAAAAD/EADIAAAAACMAAhQKAAH//wAAAAAA/woE////AP//AAD/////EQD+AAAAAA=="),
    "night": (2197, "Ah0AAAAFAAGWBQGWMjIC3DICAAD/nADIAAAAAAAAACAAAAADAgGWBQHXMjICADIDiwD/AAAAAAD/AAAAAAAAAA=="),
    "sleep": (2198, "ASAAAAAFAAFMMwGWMjIC3DID/38A/0EA/7AAAAAAAAAAAA=="),
    "morning": (2199, "Ah0AAAABAAHIMgFkMjIAyDIC////AP//AAAAAAAAABoAAgoBAgH/KAG0MjIAADIBAP+WAAAAAAAAAA=="),
    "afternoon": (2200, "Ah0AAAABAAH//wAAAAAA3DIC////AP//AAAAAAAAAB0AAgoBAgH/KAHXAAAA+jICAMX/////AAAAAAAAAA=="),
    "work": (2201, "AR0AAAABAgH//wAAAAAA+pYC////j///AAAAAAAAAA=="),
    "leisure": (2202, "AiAAAAABAgH/MgAAAAAA9TID/wAA/2wA/38AAwCAAAAAAB2gAAAFAgH/MgD/FBQA8DIC/1AA7AAmAwCAEQD8AA=="),
    "meditation": (2203, "AiMAAAABAgHnNQAAAAAAblMEKwf/Bhz+Bkb+B3v/AwAcAAAAAB0AAQAKAgH/MgAAMgAA+jICAAB4AABQAwCAAAAAAA=="),
    "colorful": (2204, "ASYAAgoFAAH//wCeAAAB9QAF8QAd/3UA/8AA/0sA/1h7AAD/AAH6Aw=="),
    "candy": (2205, "ASMAAAAKAAH//wAAFBQCABQE/0pV/1UhpP5eVvv+AACAAACAAA=="),
    "dreamlike": (2206, "AiMAAAAEAgH/UACAFBQDtgoEElP+iwD/MU7/iwD/AAD6AACAACAAAggBAAH//wM9CgoA/gED////AP//Nsn+AADuAACAAA=="),
    "dreamland": (2207, "BRoAAQACAAH//wCAFBQB/xQB2gf/FQD9AACAARoAAQACAAH//wCAFBQB/xQB/7cHFQH9AACAARoAAQACAAH//wCAFBQB/xQB/zkHEQL6AwCAARoAAQACAAH//wCAFBQB/xQB/wbZFQD6AACAAR0AAAAKAAH//wCAFBQAwxQC/0AH/weNBQT3AACAAA=="),
    "energetic": (16,),
    "profound": (2208, "AiMAAAAKAgH/CgIAAAACAAAEAAD/AHr/AMf/AP//EAH6AAAAACMAAAAKAgH/CgIAAAACAAAEAAD/AHH/ALL/AP//EgH6AAAAAA=="),
    "quiet": (2209, "ASAAAAAIAgH/MgHIMhQC+jIDbv8A1f8A1f8AEQKAAAAAAA=="),
    "warm": (2210, "AyNQAQAPAgH/CgIAAAACAAAE/wAA/1oA/3gA5QA2EAD6AAAAACMAAQAPAgH/CgIAAAACAAAE/wAA/1oA/3gA8gAcEAD6AAAAABoAAAABAgGWMgAAAAAA+jIB/4H/EQCAAAAAAA=="),
    "flow": (2211, "ASkAAQAyAgH/MgD/MhkB/AAGAP//AKP/AHT/AAAAAAAAAAAAAAAAAAAAAA=="),
    "longing": (2212, "AiMAAAACAgH/MgHIMlAB0zIEAAD/AHr/swCb/zP/AAAAAAAAACMAAg8FAgH/CgPIMjIByDIEjAD/AHH/iwD//0n/FAGWAAAAAA=="),
    "happy": (2213, "BSkAAAAIAAH/AAP/ZGQCADIG/wAA/38A//8AAP//AAD/AP8AEgD8AAAAAhoRAAABAgH/AAAAAAAA/zIBiwD/AAAAEgH8ARoTAAABAgH/AAAAAAAA/zIBAAD/AAAAEgH8ARoVAAABAgH/AAAAAAAA/zIBAP8AAAAAEgH9ARoVAAABAgH/AAAAAAAA/zIBAP//AAAAEgH8AQ=="),
    "mysterious": (2214, "AikAAAABAAH/AAH/ZGQA/AMG/wAAAP8AAAD//38A//8AiwD/AAAAAAAAAikAAAAIAAH/AAP/ZGQCADIG/3D//38A//8AAP//AKD/AP8AEgD8AAAAAg=="),
    "release": (2215, "AiZQAQAFAAH/AAAAZAoCyBQFAAD/AP//AP8A//8A/38AFgD9AAAAACZVAQAFAAH/AAAAZAoCyBQFAAD/AP//AP8A//8A/38AFAD8AAAAAA=="),
    "game": (2216, "AiYAAAAFAAH//wAAAAAC/zIFiwD/AAD//xP//38A/wAAEwH9AAAAACYAAAADAAH//wAAAAAC/zIFiwD/AAD/AAAA////AP//EwH8AAAAAA=="),
    "disco": (2217, "AiwAAgoFAgH//wAAAAAB/wAH/wAAAP//AAD/////AAD//wAAiwD/AAD/EAH4ACkAAgoDAgH/CgAZAAAC/zIGiwD/AAD/AAAA////AAAA/wAAAwCAEgH6AA=="),
    "optimistic": (2218, "ASAAAQAKAAHl5QAAFBQBAAED/2iN//JuGP6DAACAAACAAA=="),
    "heartbeat": (2219, "Ah0AAAACAgH/AAEAFBQCABQC/wf7B/P/AACAAACAAB0AAAABAgH/BAOAFBQA/AUC/wAAAAAAAACAAACAAQ=="),
    "cheerful": (2220, "Ax1QAQAFAAH//wGAFBQBgBQC/38A/wAAFQD6AACAAR1VAQAFAAH//wGAFBQBgBQC/38A/wAAFwD6AACAASAAAAADAAFtbQD5FBQCABQD//8A/4Un//8AAgD4AACAAA=="),
    "swing": (2222, "BSMgAQACAgH/AAD/FBQA/xQE/0EA/4IA1ABX/5YAEQD8AAAAACMiAQACAgH/AAD/FBQA/xQE/0EA/2MA4wA5/7kAEQD6AAAAACMkAQACAgH/AAD/FBQA/xQE/0EA/2MA3gBE/7AAEQD7AAAAACMmAQACAgH/AAD/FBQA/xQE/0EA/5YA1QBV/64AEQD6AAAAACMoAQACAgH/AAD/FBQA/xQE/0EA/5YA7QAk/7IAEQD6AAAAAA=="),
    "flash": (2223, "ASagAQAIAAH//wAAAAAA/hQF//8A/38A/0UA/wAA2wBIFAH9AAAAAA=="),
    "fight": (2224, "BSMgAQACAgH//wD/FBQB/wYE/wAAAP////8AAP8AFAD5AACAACMkAQACAgH//wD/FBQB/wYE/wAAAP8A//8AAP//FgD6AACAACMiAQACAgH//wD/FBQB/wYE/wAAAP8A//8AAP//FAD7AACAACMmAQACAgH//wD/FBQB/wYE/wAAAP8A//8AAP//FgD7AACAACMoAQACAgH//wD/FBQB/wYE/wAAAP8A//8AAP//EAD5AACAAA=="),
    "stacking": (2225, "AiAAAAABAAH//wAAAAAAyDID/wAAAP8AAAD/FADOAAAAACAAAQABAAH//wAAAAAAyDID/wAAAP8AAAD/EgD/AAAAAA=="),
    "twinkle": (8,),
    "breathe": (10,),
    "spin": (2226, "BSYgAAABAgH/fgOACgoA8xQF/4wH//4HYf4IB/6uB7r+FQD4AACAACkiAAABAgH/GAOACgoA8xQG/4wH//4H/14H/wY9/wbTtAb+FwD4AACAACkkAAABAgH/GQOACgoA8hQG/4wH//4HCP+qBtr+CH3+1wb/FQD4AACAACkmAAABAgH/GQOACgoA8xQG/4wH//4H/waF9Qf/Vmb/B6L/FwD4AACAACkoAAABAgH/GQOACgoA8xQG/4wH//4H8VD/B2n/CP+RCP8PFQD4AACAAA=="),
    "rhythm": (2227, "AykkAAABAAH/AACAFBQAgAEG/wAAAAD///8AAP8AiwD//38AAACAAACAAClAAgQBAAH/AACAFBQB5gQG/wYbBwf///8AAP8A/38AAP//EgDyAADZASlGAgQBAAH/AACAFBQB5gQG/wAAAAD///8AAP8A/38AAP//EADzAACAAQ=="),
    "bloom": (2228, "BCkwAAABAAH//wCAFBQB8hQG/wAA/38AcP6aB3H/9Rf///8AFgD5AACAACkjAAABAAH//wCAFBQB8hQG/wAA/38AcP6aByz//hH+//8AFAD6AACAACklAAABAAH//wCAFBQB8hQG/wAA/38AcP6aB1z//wf3//8AFgD6AACAACk3AAABAAH//wCAFBQB8hQG/wAA/38AcP6aB1n/8wf///8AFAD6AACAAA=="),
}
# fmt: on

SCENES: dict[str, SceneEntry] = {k: SceneEntry(*v) for k, v in _RAW.items()}


def get_scene_names() -> list[str]:
    return sorted(SCENES.keys())
